version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: financeapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: financeapp
      POSTGRES_USER: financeapp
      POSTGRES_PASSWORD: financeapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: financeapp-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@financeapp.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
